### ISSUE TITLE
Change ruby version constraint

### ISSUE THREAD

**Issue by golyalpha** [cqfn/pdd#113]
The current ruby interpreter version constraint is not ideal.  
'>=2.2' implies that '3.*' versions are fine as well. While there currently isn't a 3.x version of Ruby, it could potentially contain code breaking changes, once it is released, and could cause unnecessary bug reports caused by someone using the incorrect version of the interpreter.

I propose a change of the version constraint from '>=2.2' to '~>2.2', which would prevent such behavior.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#113](https://github.com/yegor256/pdd/issues/113) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @golyalpha[/z](https://www.0crat.com/u/golyalpha)

**Comment by 0crat** [comment]
The job [#113](https://github.com/yegor256/pdd/issues/113) assigned to @dferdian[/z](https://www.0crat.com/u/dferdian), here is [why](https://www.0crat.com/footprint/C3T46CUJJ/2610567818); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@dferdian[/z](https://www.0crat.com/u/dferdian) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by mbao01** [comment]
@golyalpha work has been done on this, please can you close this issue? Thank you

@yegor256 please can you add a label (probable `done` or `merged` or anything) to indicate that this issue has been worked on, i.e PR accepted and merged? Thank you :)

**Comment by yegor256** [comment]
@mbao01 only the author of the ticket can confirm that it's fixed. Let's wait a bit.

**Comment by golyalpha** [comment]
@mbao01 I see that it's been merged in #169, closing the issue.
