### ISSUE TITLE
Document more TODO patterns

### ISSUE THREAD

**Issue by php-coder** [cqfn/pdd#115]
#106 adds more patterns for TODO entries that aren't documented. It would be good to have them documented on https://github.com/yegor256/pdd/blob/master/README.md#how-to-format

**Comment by mbao01** [comment]
This issue has been resolved in #161. We can close this issue @yegor256

**Comment by mbao01** [comment]
@yegor256 Please close this issue. Thank you

You can reopen this issue if not resolved @php-coder
