### ISSUE TITLE
[bug][regression] fails on TODO word inside of the XML tag

### ISSUE THREAD

**Issue by php-coder** [cqfn/pdd#117]
With the latest changes, pdd can't parse the following valid CheckStyle configuration:
```console
$ grep -1 TODO src/main/config/checkstyle.xml
        <module name="TrailingComment">
            <property name="legalComment" value="TODO|XXX|NOPMD"/>
        </module>
```
Error:
```
Reading src/main/config/checkstyle.xml...
ERROR: src/main/config/checkstyle.xml; puzzle at line #272; TODO must have a leading space to become a puzzle, as this page explains: https://github.com/yegor256/pdd#how-to-format
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@php-coder[/z](https://www.0crat.com/u/php-coder) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T46CUJJ) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@php-coder I believe the only solution here is to `--exclude` this file in your `.pdd` config. What would you suggest otherwise?

**Comment by php-coder** [comment]
@yegor256 Could we update the rules/regexp to not treat `value="TODO` as a comment? It obviously isn't a comment at all.

**Comment by yegor256** [comment]
@php-coder how about we add something like this:

```
--exclude-regex='value="TODO'
```

WDYT?

**Comment by php-coder** [comment]
@yegor256 Yes, it will solve this and similar issues. Also it should be implemented on 0pdd.

**Comment by raboley** [comment]
Is there a reason it can't only match on @todo? it seems like that is the accepted pattern, but anything with the word todo
triggers and breaks pdd. such as:

```
number.ToDouble
// TODO: gotta fix this but am lazy
```

would be great if pdd could be more descriminating, since a malformatted todo breaks everything.

**Comment by mbao01** [comment]
Sequel to issues [#106](https://github.com/yegor256/pdd/issues/106) and this issue, it will be great if todo markers are configurable by the developer. Yes, we can have default todo markers to be `@todo` and `TODO:` (for backward compatibility). Then we give a configuration option to allow users to set custom markers.

Example:
```shell
$ pdd --markers @todo,TODO:,@pdd
```

Will register 3 markers in project (`@todo`, `TODO:` and `@pdd`) which pdd will recognize to create puzzles.
_We can also restrict the number of markers. Ideally, it should be one for uniformity. This is another discussion._

Reasoning:
I think changing how developers are used to writing todos in their applications will be a tough one, considering the number of programming languages that exist today.

I will create an issue if this is a good idea @yegor256

**Comment by mbao01** [comment]
@yegor256 Please see the comment above

**Comment by mbao01** [comment]
@php-coder work has been done on this, please can you close this issue? Thank you

@yegor256 please can you add a label (probable `done` or `merged` or anything) to indicate that this issue has been worked on, i.e PR accepted and merged? Thank you :)

**Comment by AntistasII** [comment]
@yegor256 Could you please look at Ayomide's comment?

**Comment by yegor256** [comment]
@mbao01 I'm closing, thanks!
