### ISSUE TITLE
rake_task.rb:10-12: Needs to have more parameters to run...

### ISSUE THREAD

**Issue by 0pdd** [cqfn/pdd#132]
The puzzle `125-7d80a284` from #125 has to be resolved: 

https://github.com/yegor256/pdd/blob/9ff4023b83610ccd06acce934d321ff2edeec35c/lib/pdd/rake_task.rb#L10-L12

The puzzle was created by Alexey Vinogradov on 10-Jul-19. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#132](https://github.com/yegor256/pdd/issues/132) is now in scope, role is `DEV`

**Comment by aivinog1** [comment]
@yegor256 Can you assign this issue to me, please?

**Comment by mbao01** [comment]
@yegor256 please can you clarify? The description for this task is not clear. It seems related to another puzzle.

**Comment by Doldrums** [comment]
@yegor256 close issue pls

**Comment by Doldrums** [comment]
@yegor256 actually, this puzzle is already removed 
https://github.com/cqfn/pdd/blob/13012efa642fe265cd8b7695d5ab4317a801fde3/lib/pdd/rake_task.rb#L15
is 0pdd checks between several latest commits?

**Comment by yegor256** [comment]
@mbao01 let me try
