### ISSUE TITLE
rake_task.rb:24-26: need to implement this method. For...

### ISSUE THREAD

**Issue by 0pdd** [cqfn/pdd#133]
The puzzle `125-db127bd1` from #125 has to be resolved: 

https://github.com/yegor256/pdd/blob/9ff4023b83610ccd06acce934d321ff2edeec35c/lib/pdd/rake_task.rb#L24-L26

The puzzle was created by Alexey Vinogradov on 10-Jul-19. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#133](https://github.com/yegor256/pdd/issues/133) is now in scope, role is `DEV`

**Comment by aivinog1** [comment]
@yegor256 Can you assign this issue to me, please?

**Comment by mbao01** [comment]
@yegor256 please can you clarify? The description for this task is not clear. What is the problem to solve here?

**Comment by AntistasII** [comment]
@yegor256 Could you please give some clarification for this issue ?

**Comment by yegor256** [comment]
@mbao01 just remove the puzzle from the code. It duplicates another one in the same file.

**Comment by Doldrums** [comment]
@yegor256 are u sure that it duplicates? could u pls refer to which one

**Comment by yegor256** [comment]
@mbao01 @Doldrums I'm not the author of the puzzle. You can't find answers from me :) Just deal with the puzzle: either delete it or fix.

**Comment by yegor256** [comment]
@Doldrums closed
