### ISSUE TITLE
.rubocop.yml:19-21: Needs to enable this check and fix...

### ISSUE THREAD

**Issue by 0pdd** [cqfn/pdd#134]
The puzzle `123-9786ef4c` from #123 has to be resolved: 

https://github.com/yegor256/pdd/blob/639dac606fa77d510f9da2c77d76850a65148877/.rubocop.yml#L19-L21

The puzzle was created by Alexey Vinogradov on 10-Jul-19. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#134](https://github.com/yegor256/pdd/issues/134) is now in scope, role is `DEV`

**Comment by aivinog1** [comment]
@yegor256 Can you assign this issue to me, please?

**Comment by mbao01** [comment]
@yegor256 for some reason, after removing the comments and merging the PR that fixes this, 0pdd did not close the issue. Please can you close it?

**Comment by yegor256** [comment]
@mbao01 let's try
