### ISSUE TITLE
pdd does not feature --include option

### ISSUE THREAD

**Issue by ribtoks** [cqfn/pdd#138]
I'm trying to run `pdd` on a repository with multiple technologies used (main repository language is C/C++). `pdd` scans all kinds of files, however it would only need to scan `*.c, *.cpp, *.h, *.hpp` files for me. Currently only `--exclude` option is supported, however, I'm not going to write all the regexes in order to exclude all other 10 types of files in my repo. If `pdd` would support `--include` option it would save the day. Another proper fix for this problem would be to consume input files from `stdin` that would enable to integrate `pdd` with unix pipes like `find . -name "*.cpp" | pdd` or `find . -name "*.cpp" -exec pdd {};`.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@ribtoks[/z](https://www.0crat.com/u/ribtoks) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T46CUJJ) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@ribtoks definitely a good idea. Would you be interested to submit a pull request?

**Comment by mbao01** [comment]
@ribtoks work has been done on this, please can you close this issue? Thank you

@yegor256 please can you add a label (probable `done` or `merged` or anything) to indicate that this issue has been worked on, i.e PR accepted and merged? Thank you :)
