### ISSUE TITLE
pdd fails to parse files in a charset other than UTF-8

### ISSUE THREAD

**Issue by php-coder** [cqfn/pdd#143]
I have a file in windows-1251 charset and when I committed it into a repo, pdd has started to fail with the following error:

> ERROR: src/test/wiremock/__files/series/import/request-logic/charset-windows-1251.html; puzzle at line 7; invalid byte sequence in UTF-8

Here is the comment that 0pdd posted: https://github.com/php-coder/mystamps/commit/a4d9ef2c3634f695101c1fa3d1b21568b3dad8cf#commitcomment-37196757

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@php-coder[/z](https://www.0crat.com/u/php-coder) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T46CUJJ) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@php-coder this indeed may be a bug. Would you be interested in submitting a pull request to fix it?

**Comment by php-coder** [comment]
@yegor256 As it's not critical to me (there is a workaround), I'm not interested in dealing with Ruby code :)

**Comment by firedev** [comment]
Seems like a non-issue. CP-1251? Come on. It's UTF-8 that needs attention. https://github.com/cqfn/pdd/issues/164

**Comment by mbao01** [comment]
<img width="557" alt="Screenshot 2021-09-06 at 08 31 24" src="https://user-images.githubusercontent.com/10655408/132180560-d3b15c85-25b3-42a7-b572-80387a47cd87.png">

<img width="402" alt="Screenshot 2021-09-06 at 08 30 53" src="https://user-images.githubusercontent.com/10655408/132180541-11129d60-2848-450d-90b1-fea7d0ec19c5.png">
