### ISSUE TITLE
Rakefile:21-23: Hey, take a look at test_source.rb:192. I...

### ISSUE THREAD

**Issue by 0pdd** [cqfn/pdd#155]
The puzzle `153-0452b4a7` from #153 has to be resolved: 

https://github.com/yegor256/pdd/blob/54a2f17660bc9f6eeeb28fec7b2506046e4873c2/Rakefile#L21-L23

The puzzle was created by @yegor256 on 30-Jun-21. 

Estimate: 60 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by mbao01** [comment]
@yegor256 please close this issue. This issue has been resolved and its puzzle removed from the source code.
