### ISSUE TITLE
UTF-8 is encoded

### ISSUE THREAD

**Issue by firedev** [cqfn/pdd#164]
Russian letters come out like this `&#x41E;&#x431;&#x440;` looks like Ruby 1.9 UTF-8 workaround. I think it is safe to assume that we are living in UTF-8 world. And ruby 2.x at least. First few 2.x versions are end-of-the-line already.

```
  <puzzle>
    <ticket>85</ticket>
    <estimate>0</estimate>
    <role>DEV</role>
    <id>85-b6aa97f4</id>
    <lines>1-1</lines>
    <body>&#x41E;&#x431;&#x440;&#x430;&#x431;&#x43E;&#x442;&#x43A;&#x430;</body>
    <file>bug</file>
  </puzzle>
```

**Comment by php-coder** [comment]
> I think it is safe to assume that we are living in UTF-8 world

While I disagree with that statement, if you go this way, please, document this assumption at least.

**Comment by mbao01** [comment]
@yegor256 please can you add a label (probable `done` or `merged` or anything) to indicate that this issue has been worked on, i.e PR accepted and merged? Thank you :)

**Comment by AntistasII** [comment]
@yegor256  Could you look at Ayomide's comment, please?

**Comment by yegor256** [comment]
@mbao01 is it fixed?

**Comment by mbao01** [comment]
Yes, please see my comment above @yegor256 
https://github.com/cqfn/pdd/pull/172

**Comment by mbao01** [comment]
@AntistasII Please can we close this issue?

**Comment by AntistasII** [comment]
if issue is fixed , so yes.
@yegor256  what should we do to close that? @mbao01 fixed it...

**Comment by yegor256** [comment]
@AntistasII @mbao01 @firedev I'm closing, thanks all
