### ISSUE TITLE
Proposal: Format error messages as `path/file:line`

### ISSUE THREAD

**Issue by firedev** [cqfn/pdd#165]
In some terminals (iTerm) you can click and open files on the offending line. For this to work it should be written as `path/to/file:99` where 99 is line.

Look at `rspec` output for example. 

I propose to use the same format:

Before:
```
ERROR: spec/java/_5_TestSaleWithDiscount_spec.rb; puzzle at line #47; TODO found
```
After:
```
ERROR: spec/java/_5_TestSaleWithDiscount_spec.rb:47 TODO found
```

**Comment by mbao01** [comment]
Thanks, @firedev I agree with you. Some error messages are formatted correctly. This will be fixed 💯

**Comment by mbao01** [comment]
Hi @firedev this issue has been resolved. Please confirm and close the issue. Thank you.

**Comment by firedev** [comment]
@mbao01 it is probably not released yet

```

$ gem install pdd
Successfully installed pdd-0.20.6
1 gem installed

$ pdd
ERROR: app/models/product.rb; puzzle at line #14;

```

**Comment by yegor256** [comment]
@rultor release, tag is `0.20.7`

**Comment by yegor256** [comment]
@mbao01 @firedev version 0.20.7 is released, try it please

**Comment by firedev** [comment]
@yegor256 I needed pdd to validate TODOs for @0pdd. Unfortunately 0pdd kept crashing due to https://github.com/yegor256/0pdd/issues/304 So I had to abandon the whole idea, format TODOs back and use todo parser from github actions.

**Comment by mbao01** [comment]
@yegor256 please can you add a label (probable `done` or `merged` or anything) to indicate that this issue has been worked on, i.e PR accepted and merged? Thank you :)

**Comment by mbao01** [comment]
@firedev work has been done on this, please can you close this issue? Thank you

**Comment by AntistasII** [comment]
@firedev @yegor256 please consider the closing of this issue?
