### ISSUE TITLE
Add pre-commit and pre-push hooks to automatically lint and run tests

### ISSUE THREAD

**Issue by mbao01** [cqfn/pdd#167]
Description
This issue is focused on developer experience. I want _rake_ tasks to run locally before I push code to the central repo. This helps to catch issues that would have otherwise been caught later in future, leading to rework and time loss.

**Acceptance Criteria**
- Before-commit:
pre-commit hooks should reformat commit message to the format:
`#[BRANCH_NAME]: [MESSAGE]`

- Before push:
pre-push hooks should run _rake_ tasks and only push code when all tests pass. Command to run and succeed before push;
`bundle exec rake`

- Document tool used and setup in README

Resources:
[Overcommit](https://github.com/sds/overcommit) tool to manage and configure git hooks
[Medium post on Overcommit](https://kirillshevch.medium.com/lint-your-ruby-code-with-overcommit-and-static-analysis-tools-bd36d3147d2e)

**Comment by mbao01** [comment]
I think it is possible. I have used [husky](https://www.npmjs.com/package/husky) with projects on github. Husky (typescript) can also be used with this project but I prefer Overcommit to keep everything in Ruby. I can set this up :)

**Comment by yegor256** [comment]
@yegor256 what about other programmers, who don't want to have such hooks (I'm one of them). Will this be optional or mandatory for everybody?

**Comment by mbao01** [comment]
It is mandatory, not optional. It is one project so we need a level of consistency and code checks before any developer pushes to this project. It is important for any project (especially open source).
@yegor256

**Comment by yegor256** [comment]
@mbao01 Well, we have a quality control enforced by Rultor. How exactly each programmer organizes their development environment, I believe, we should not enforce. I, for example, don't like the idea of running full build on `git push`. I'm used to having `git push` finish immediately, not after a few minutes.

**Comment by mbao01** [comment]
I think the commands run on prepush or other hooks is something the team should agree on. All this is to prevent bugs from creeping in and save developer time. I like this experience. It defeats the purpose if it's optional and some people can turn it off. We can decide on appropriate prepush command (or remove it entirely) since that's the pain point.

**Comment by mbao01** [comment]
I will close this issue. A new issue can be opened to continue this conversation @yegor256
