### ISSUE TITLE
Extend `bundle exec rake` checks for corresponding puzzles conditions

### ISSUE THREAD

**Issue by Doldrums** [cqfn/pdd#175]
Actually, now while running `bundle exec rake` locally there is no opportunity to check if puzzles in the source code correspond to their conditions. This will help to avoid possible failures of `@rultor merge` command after reviewing PRs.

**Comment by mbao01** [comment]
Yes, that is correct @Doldrums. The way I see it, this is outside the scope of `pdd` (as a puzzle generator). If you use the core library `pdd` directly (locally) in your project in some pre-commit/pre-push stage, it is possible you can catch these errors.

Unfortunately, you don't need to have `pdd` installed locally in your project when using `0pdd`. Thus, there's no way to tell if your puzzles are badly formatted or not before pushing to remote. Ideally, this is the job of code quality tools, but I don't know of any tool that can specifically match the rules for puzzle markers.
