### ISSUE TITLE
Default `--include` option array of files does not depend on `--source` option value

### ISSUE THREAD

**Issue by Doldrums** [cqfn/pdd#176]
In some way, it was a temporary solution because now the default array of files for pdd is collecting from the current working directory.   But ideally this array should depend on the specified (or not) directory via `--source`.
https://github.com/cqfn/pdd/blob/f07f2786939e8705f8e1a88510878af29ea7baaf/bin/pdd#L45-L49

**Comment by mbao01** [comment]
@Doldrums Could you possibly close this issue, it has been worked on.
