### ISSUE TITLE
too much consumed into puzzle body

### ISSUE THREAD

**Issue by yegor256** [cqfn/pdd#209]
This is my code:

```
@todo #42 hello
 good bye
hello again
```

This is what pdd 0.21.1 generates as puzzle body:

```
hello good bye hello again
```

I expect it to be:

```
hello good bye
```

The problem is urgent, since we generate wrong puzzles now, for example: https://github.com/yegor256/takes/issues/1131

**Comment by yegor256** [comment]
@mbao01 please, help us

**Comment by yegor256** [comment]
@php-coder this should be fixed soon and will help

**Comment by mbao01** [comment]
I guess to keep this backward compatible, if a todo comment uses the indentation style, then we body will be the first line till the last indented line.
