### ISSUE TITLE
year in files should be updated

### ISSUE THREAD

**Issue by BogdanDor** [cqfn/pdd#218]
`bundle exec rake`  `completed with exit code 1` and output at the end 

> Running xcop...
> Inspecting 2 files...
> ..
> 2 files checked, everything looks pretty
> grep -q -r '2014-2023'     --include '*.rb'     --include '*.txt'     --include 'Rakefile'     .
> rake aborted!
> Command failed with status (1): [grep -q -r '2014-2023'     --include '*.rb...]
> /home/bogdan/pdd/Rakefile:85:in \`block in <top (required)>'
> /home/bogdan/.rbenv/versions/2.7.7/bin/bundle:23:in \`load'
> /home/bogdan/.rbenv/versions/2.7.7/bin/bundle:23:in `<main>'
> Tasks: TOP => default => copyright
> (See full trace by running task with --trace)

it happened because year increased.
To fix this error required change year from 2022 to 2023 in all copyright sections.

**Comment by php-coder** [comment]
Copyrights have been updated in f15a8fe504ae05fd99040386bb29120a526c13b8 commit. Perhaps, the issue can be closed.

@yegor256 please, confirm and close if you're agree.

**Comment by yegor256** [comment]
@php-coder indeed, thanks!
