### ISSUE TITLE
Puzzle Header

### ISSUE THREAD

**Issue by volodya-lombrozo** [cqfn/pdd#241]
I'd like to address the readability of issue headers in `pdd`, particularly when dealing with puzzles. Currently, the headers are not human-readable, as exemplified by the following [example](https://github.com/objectionary/jeo-maven-plugin/issues/447#issue-2110225210):
```
* @todo #431:30min Measure the assembling time and print it to logs. 
*  The assembling time should be measured in milliseconds and printed to logs. 
*  Moreover, we have to add one more log entry that would print the path of the file 
*  being assembled. The entire log should look like this: 
*  "Assembling file.xmir (5kb)....". 
*  "Assembled file.class (6kb) in 100ms". 
```
Issue Header:
```
ImprovementBytecodeFootprint.java:85-90: Measure the... #447
```
I propose a more user-friendly format, such as:
```
Measure the assembling time and print it to logs. (30min, from #issue)
```
or a simplified version:
```
Measure the assembling time and print it to logs.
```

My goal is to encapsulate all meta information directly within the puzzle description. Is there a way to configure `pdd` to generate issue headers in this human-readable format?

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you help here, please?

**Comment by yegor256** [comment]
@pnatashap maybe you can help?

**Comment by php-coder** [comment]
pdd just extracts data and populate fields in `pdd.xml`, in other words, it's a low-level tool. I believe that this should be implemented on 0pdd level.

If we look at https://github.com/yegor256/0pdd, there is parameter `short-title` that removes `ImprovementBytecodeFootprint.java:85-90:` from the title. So, it's possible to introduce another parameter for configuring title's format.

**Comment by volodya-lombrozo** [comment]
@php-coder Thank you! I'll try to use `short-title` then. If I have questions, I will ask them is `0pdd` repository.
