### ISSUE TITLE
Consider using the exclusions from .gitignore

### ISSUE THREAD

**Issue by php-coder** [cqfn/pdd#80]
If we scan a git repo, then it would be useful to use existing `.gitignore` file, so I don't need to specify all the exclusions manually (or duplicate them in a config file).

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@php-coder sounds like a good idea, let me implement it

**Comment by 0crat** [comment]
Job [#80](https://github.com/yegor256/pdd/issues/80) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#80](https://github.com/yegor256/pdd/issues/80) assigned to @danielpalafox[/z](https://www.0crat.com/u/danielpalafox), here is [why](https://www.0crat.com/footprint/C3T46CUJJ/1790862472); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@danielpalafox[/z](https://www.0crat.com/u/danielpalafox) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The job [#80](https://github.com/yegor256/pdd/issues/80) assigned to @timeracers[/z](https://www.0crat.com/u/timeracers), here is [why](https://www.0crat.com/footprint/C3T46CUJJ/1871158353); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@timeracers[/z](https://www.0crat.com/u/timeracers) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by mbao01** [comment]
This issue is more involved. _.gitignore_ contain [patterns](https://git-scm.com/docs/gitignore) that are not supported or recognized by the `Dir.glob(...)` API. A solution will be to write a matcher (specifically for _.gitignore_) on top of `Dir.glob(...)` OR use an existing _.gitignore_ pattern matcher

**Comment by yegor256** [comment]
@mbao01 which way do you prefer to go?

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@72e1d93d-facd-41ba-b3a8-f33dfa972433, thread: pool-65-thread-1
com.zerocracy.radars.github.GhProject[69] com.zerocracy.radars.github.GhProjectNotFoundException: Github project for 'cqfn/pdd' repo was not found
```

[0.55.1](https://github.com/zerocracy/farm): Issue: cqfn/pdd#80, Comment: 404393510

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@72e1d93d-facd-41ba-b3a8-f33dfa972433, thread: pool-65-thread-1
com.zerocracy.radars.github.ReSafe[81] java.io.IOException: com.zerocracy.radars.github.GhProjectNotFoundException: Github project for 'cqfn/pdd' repo was not found
com.zerocracy.radars.github.GhProject[69] com.zerocracy.radars.github.GhProjectNotFoundException: Github project for 'cqfn/pdd' repo was not found
```

[0.55.1](https://github.com/zerocracy/farm): Issue: cqfn/pdd#80, Action: `created`

**Comment by mbao01** [comment]
> @mbao01 which way do you prefer to go?

I will look for an existing _.gitignore_ file matcher. If I find one, I will use it. Plan B will be to build a custom matcher on top of `Dir.glob(...) `

**Comment by mbao01** [comment]
@php-coder work has been done on this, please can you close this issue? Thank you

@yegor256 please can you add a label (probable `done` or `merged` or anything) to indicate that this issue has been worked on, i.e PR accepted and merged? Thank you :)

**Comment by AntistasII** [comment]
@yegor256 Could you please look at Ayomide's comment?

**Comment by yegor256** [comment]
@mbao01 I'm closing, thanks!
